version: '3.7'

networks:
  flask:

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./../postgres_data:/var/lib/postgres/data
    expose: 
      - "5432"
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ocd_10_api_db
    networks: 
      - flask

  web:
    build:
      context: ./../../
      dockerfile: .devops/docker/Dockerfile
    command: python manage.py runserver -h 0.0.0.0
    volumes: 
      - ./../../:/usr/src
    ports:
      - "5000:5000"
    networks: 
      - flask
    env_file: 
      - ./../../.env
    depends_on: 
      - db
